TrajectoryPlannerROS:
   max_vel_x: 1.0
   min_vel: 0.05
   max_rotational_vel: 0.15
   min_in_place_rotational_vel: 0.01
   min_in_place_vel_theta: 0.01
   max_vel_theta: 0.15
   min_vel_theta: -0-15
   acc_lim_th: 3.0
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   holomic_robot: false
   meter_scoring: true