TrajectoryPlannerROS:
   max_vel_x: 2.0
   min_vel: 0.05
   max_rotational_vel: 2.0
   min_in_place_rotational_vel: 0.01
   min_in_place_vel_theta: 0.01
   max_vel_theta: 0.50
   min_vel_theta: -0.50
   acc_lim_theta: 3.0
   acc_lim_x: 2.5
   acc_lim_y: 2.5
   holomic_robot: true
   meter_scoring: true