# maximum range sensor reading that will result in an obstacle being put into the costmap
obstacle_range: 2.5
# range to which we will raytrace freespace given a sensor reading
raytrace_range: 3.0
# size of the robot
footprint: [[-0.4,-0.4],[-0.4,0.4],[0.4,0.4],[0.4,-0.4]]
# maximum distance from obstacles at which a cost should be incurred
inflation_radius: 0.5
# cost_scaling_factor: 10.0
observation_source: laser_scan_sensor
laser_scan_sensor: {sensor_frame: sweep_link,
max_obstacle_height: 0.85, min_obstacle_height: 0.2, data_type: LaserScan,
topic: /base_scan, marking: true, clearing: true}
