obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[-0.4,-0.4],[-0.4,0.4],[0.4,0.4],[0.4,-0.4]]
inflation_radius: 0.5
cost_scaling_factor: 10.0
observation_source: scan
scan: {sensor_frame: base_link, observation_persistence: 0.0,
max_obstacle_height: 0.85, min_obstacle_height: 0.0, data_type: LaserScan,
topic: /base_scan, marking: true, clearing: true}